FROM library/alt:sisyphus
RUN rm -rf /etc/apt/sources.list.d/* /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://mirror.yandex.ru/altlinux Sisyphus/x86_64 classic' >> \
      /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://mirror.yandex.ru/altlinux Sisyphus/noarch classic' >> \
      /etc/apt/sources.list \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y glibc-locales su sudo systemd chrony apt-repo \
        docker-ce \
    && apt-get install -y systemd-sysvinit \
    && apt-get clean \
    && find /var/lib/apt/lists/ -type f -exec rm "{}" \; \
    && rm -rf /var/cache/apt/*.bin \
    && control sudo public \
    && systemctl enable chronyd

ENTRYPOINT [ "/sbin/init" ]
