FROM library/alt:sisyphus
ENV container=docker

RUN rm -rf /etc/apt/sources.list.d/* /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://download.basealt.ru/pub/distributions/ALTLinux Sisyphus/x86_64 classic' >> \
      /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://download.basealt.ru/pub/distributions/ALTLinux Sisyphus/x86_64 debuginfo' >> \
      /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://download.basealt.ru/pub/distributions/ALTLinux Sisyphus/noarch classic' >> \
      /etc/apt/sources.list \
    && sed -i 's/^%_install_langs .*/# &/g' /etc/rpm/macros \
    && echo '%_install_langs en_US:fr_FR:C:' >> /etc/rpm/macros \
    && rm -rf /usr/lib/locale/ \
    && rm -rf /usr/share/locale/ \
    && mkdir -p /usr/share/locale/en_GB/LC_MESSAGES/ \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y branding-xalt-kworkstation-release \
    && apt-get install -y glibc-locales \
    && apt-get install -y su sudo systemd chrony apt-repo \
        docker-ce \
    && echo 'Yes, do as I say!' | apt-get install --force-yes systemd-sysvinit \
    && apt-get clean \
    && find /var/lib/apt/lists/ -type f -exec rm "{}" \; \
    && rm -rf /var/cache/apt/*.bin \
    && sed -i 's/^devpts[[:space:]]/# &/' /etc/fstab \
    && control sudo public \
    && control sudowheel enabled \
    && systemctl enable chronyd \
    && sed -i 's/mesg n/mesg n >\/dev\/null 2>\&1/g' /root/.bash_profile

ENTRYPOINT [ "/sbin/init" ]
