FROM library/alt:sisyphus
ENV container=docker

RUN rm -rf /etc/apt/sources.list.d/* /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://download.basealt.ru/pub/distributions/ALTLinux Sisyphus/x86_64 classic' >> \
      /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://download.basealt.ru/pub/distributions/ALTLinux Sisyphus/x86_64 debuginfo' >> \
      /etc/apt/sources.list \
    && echo \
      'rpm [alt] http://download.basealt.ru/pub/distributions/ALTLinux Sisyphus/noarch classic' >> \
      /etc/apt/sources.list \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y glibc-locales su sudo systemd chrony apt-repo \
        docker-ce \
    && echo 'Yes, do as I say!' | apt-get install --force-yes systemd-sysvinit \
    && apt-get clean \
    && find /var/lib/apt/lists/ -type f -exec rm "{}" \; \
    && rm -rf /var/cache/apt/*.bin \
    && control sudo public \
    && systemctl enable chronyd \
    && sed -i 's/mesg n/mesg n >\/dev\/null 2>\&1/g' /root/.bash_profile

ENTRYPOINT [ "/sbin/init" ]
